
Mon, 25 Mar 2019 11:59:58 GMT

COMMAND LINE:
/usr/bin/graalpython fasta.graal-3.graal 2500000

PROGRAM FAILED 


PROGRAM OUTPUT:

Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Traceback (most recent call last):
  File "fasta.graal-3.graal", line 138, in <module 'fasta.graal-3.graal'>
    main()
  File "fasta.graal-3.graal", line 127, in main
    repeat_fasta(alu, n * 2)
  File "fasta.graal-3.graal", line 52, in repeat_fasta
    s = bytearray(ss, encoding='utf8')
TypeError: got an unexpected keyword argument 'encoding'
