
Mon, 22 Jun 2015 11:13:15 GMT

COMMAND LINE:
/usr/bin/python3.5 pidigits.python3.5-3.python3.5 2000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "pidigits.python3.5-3.python3.5", line 10, in <module>
    from gmpy2 import mpz
ImportError: No module named 'gmpy2'
