
Wed, 18 Jan 2017 10:05:46 GMT

COMMAND LINE:
/usr/bin/pypy pidigits.pypy-3.pypy 10000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "pidigits.pypy-3.pypy", line 10, in <module>
    from gmpy import mpz
ImportError: No module named gmpy
