
Wed, 21 Dec 2016 14:54:29 GMT

COMMAND LINE:
/usr/bin/ipy pidigits.ipy-4.ipy 10000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "pidigits.ipy-4.ipy", line 10, in <module>
ImportError: No module named gmpy_cffi
