
Tue, 13 Sep 2016 17:55:06 GMT

COMMAND LINE:
/usr/bin/python3.7 pidigits.python-dev-2.python-dev 2000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "pidigits.python-dev-2.python-dev", line 7, in <module>
    from gmpy2 import mpz
ModuleNotFoundError: No module named 'gmpy2'
