
 Fri, 30 Oct 2020 20:17:24 GMT

COMMAND LINE:
 /usr/bin/pypy pidigits.pypy-3.pypy 10000

PROGRAM FAILED 


PROGRAM OUTPUT:

Traceback (most recent call last):
  File "pidigits.pypy-3.pypy", line 13, in <module>
    from gmpy_cffi import mpz
ImportError: No module named gmpy_cffi
